# Generated by go2rpm 1.19.0
%bcond check 0

# https://github.com/lxc/distrobuilder
%global goipath         github.com/lxc/distrobuilder
Version:                3.3.1

%gometa -L -f


Name:           distrobuilder
Release:        %autorelease
Summary:        System container image builder for LXC and Incus

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND MPL-2.0 AND Unlicense
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools
BuildRequires:  btrfs-progs-devel
BuildRequires:  gpgme-devel

Requires: /usr/bin/hivexregedit
Requires: /usr/bin/wimlib-imagex

%description
System container image builder for LXC and Incus.

%prep
%goprep -p1
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/distrobuilder ./distrobuilder

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%doc doc AUTHORS CODE_OF_CONDUCT.md CONTRIBUTING.md README.md
%doc .sphinx/requirements.txt .sphinx/wordlist.txt
%doc .sphinx/.markdownlint/exceptions.txt
%{_bindir}/distrobuilder


%changelog
%autochangelog
